server {
    listen       80;
    listen  [::]:80;
    server_name  blog.bustikiller.com;

    root   /usr/share/nginx/html;
    index  index.html index.htm;

    location = / {
    }

    location / {
        try_files $uri $uri.html $uri/ /404.html;
    }

    # Redirect URLs without a trailing slash to the version with a trailing slash
    # rewrite ^(/tags)$ $scheme://$host$1/ permanent;

    error_page  404              /404.html;
}